#+title: Anotação ao artigo 23.º da CH1996
#+author: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil author:nil date:nil title:nil

#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{titletoc}
#+LATEX_HEADER: \KOMAoptions{headings=small}

#+bibliography: ~/Dropbox/Bibliografia/BetterBibLatex/bib.bib
#+cite_export: csl np405.csl

#+begin_quote

*Artigo 23.º*

1. As medidas tomadas pelas autoridades de um Estado Contratante serão reconhecidas por força de lei em todos os outros Estado Contratantes.

2. Todavia, o reconhecimento poderá ser recusado:

  a) Se a medida tiver sido tomada por uma autoridade cuja competência não assenta em nenhum dos fundamentos previstos no capítulo II;

  b) Se a medida tiver sido tomada, salvo em caso de urgência, num contexto de um processo judiciário ou administrativo, sem se ter concedido à criança a possibilidade de ser ouvida, violando os princípios fundamentais dos procedimentos do Estado requerido;

  c) Se qualquer pessoa apresentar pedido indicando que a medida infringe as suas responsabilidades parentais, se tal medida tiver sido tomada, salvo em casos de urgência, sem se ter concedido a essa pessoa a possibilidade de ser ouvida;

  d) Se tal reconhecimento é manifestamente contrário à ordem pública do Estado requerido, tendo em conta os melhores interesses da criança;

  e) Se a medida for incompatível com outra medida posterior tomada no Estado não Contratante da residência habitual da criança, quando esta última medida preencha os requisitos necessários ao reconhecimento no Estado requerido;

  f) Se os procedimentos previstos no artigo 33.º não tiverem sido respeitados.

#+end_quote

*Sumário:* 1. Breves notas gerais sobre o Capítulo IV; a) Articulação com o regime de reconhecimento e execução do Regulamento Bruxelas II /ter/; b) Objeto do reconhecimento e execução; 2. Reconhecimento automático (n.º 1); 3. Fundamentos de recusa do reconhecimento (n.º 2); a) Aspetos gerais; b) Controlo da competência da autoridade do Estado Contratante de origem; c) Não audição da criança; d) Não audição da pessoa com responsabilidades parentais; e) Violação da ordem pública internacional; f) Incompatibilidade de medidas de proteção; g) Preterição dos procedimentos previstos no artigo 33.º; 4. Bibliografia; 5. Jurisprudência.

* 1. Breves notas gerais sobre o Capítulo IV
** a) Articulação com o regime de reconhecimento e execução do Regulamento Bruxelas II /ter/
A CH 1996 regula a competência, a lei aplicável, o reconhecimento (em sentido amplo) e a cooperação em matéria de responsabilidade parental e medidas
de protecção das crianças. O Regulamento Bruxelas II /ter/ regula a competência e o reconhecimento (em sentido amplo) em matéria matrimonial e em
matéria de responsabilidade parental, bem como o rapto internacional de crianças. Há, por isso, uma coincidência parcial de matérias reguladas por estes dois instrumentos. Ambos regulam a competência e o reconhecimento (em sentido amplo) em matéria de responsabilidade parental. O conceito de responsabilidade parental adotado pelo Regulamento Bruxelas II /ter/ é inspirado no consagado pela CH 1996 [cite:@almeida2022 pp. 21-22;@magnus2023a pp.86-87;@gomes2023 pp. 1561-1562].

A articulação entre estes dois instrumentos efetua-se atendendo ao artigo 52.º CH 1996 (para cuja anotação se remete) e ao artigo 97.º Regulamento Bruxelas II /ter/ [cite:@almeida2022 p. 29;@goncalves2023 pp. 61-63]. O artigo 52.º foi precedido de longas e complexas negociações. Os Estados-Membros da União Europeia pretendiam reservar para si o direito de celebrar uma convenção sobre competência internacional em matéria de responsabilidade parental e ações matrimoniais. Os outros Estados Contratantes da Conferência da Haia receavam o enfraquecimento da CH 1996, caso fosse conferida a possibilidade de Estados Contratantes celebrarem entre si e com Estados terceiros novas convenções sobre a mesma matéria. A redação do artigo 52.º CH 1996 traduz o compromisso alcançado [cite:@lagarde1996, n.º 170]. O n.º 2 do artigo 52.º confere a possibilidade de os Estados Contratantes celebrarem acordos entre si, em matéria de responsabilidade parental, relativamente a crianças habitualmente residentes no território desses Estados Contratantes. O requisito da residência habitual das crianças suscita dúvidas, particularmente no contexto da aplicação das normas de reconhecimento [cite:@gomes2023 p. 1598].

Neste contexto, e porque só podem ser Partes na CH 1996 Estados soberanos, o Conselho autorizou os Estados-Membros da União Europeia a ratificar ou aderir à CH 1996, mas exigiu - para garantir a aplicação das regras de Direito da União Europeia relativas ao reconhecimento e à execução de decisões judiciais na União Europeia - que os Estados-Membros fizessem a seguinte declaração ao assinar a Convenção:
#+begin_quote
"Os artigos 23.º, 26.º e 52.º da Convenção permitem às Partes Contratantes uma certa margem de flexibilidade para aplicarem um sistema simples e rápido de reconhecimento e de execução das decisões. A regulamentação comunitária prevê um sistema de reconhecimento e de execução, pelo menos, tão favorável como as regras constantes da Convenção. Assim sendo, as decisões em matérias abrangidas pela Convenção, quando proferidas por um tribunal de um Estado-Membro da União Europeia, serão reconhecidas e executadas em/na/nos [Estado-Membro que faz a declaração], aplicando-se a regulamentação interna pertinente do direito comunitário."[fn:1]
#+end_quote

Na alínea /b)/ do n.º 1 do artigo 97.º Regulamento Bruxelas II /ter/ estabelece-se que as regras de reconhecimento e execução do Regulamento Bruxelas II /ter/ prevalecem sempre (e independentemente do onde residir habitualmente a criança) sobre as da CH 1996, quando o Estado de origem e o Estado de reconhecimento sejam Estados-Membros da União Europeia vinculados ao Regulamento Bruxelas II /ter/. Assim, por exemplo, uma medida de proteção decretada na Itália deve ser reconhecida e executada em Portugal segundo o regime previsto no Regulamento Bruxelas II /ter/, mesmo que a criança resida habitualmente em Marrocos (Estado Contratante da CH 1996).  Esta solução — que parece visar uma mais fácil “circulação” das decisões no espaço europeu, assente no princípio da confiança mútua — acarreta, nos casos em que a criança tenha residência habitual num Estado terceiro que seja um Estado contratante da Convenção da Haia de 1996, um risco de se reconhecerem decisões, ao abrigo do regime do Regulamento Bruxelas II /ter/, cujo reconhecimento poderia ser recusado ao abrigo do regime da CH 1996, /v.g./, porque neste útlimo regime se admite como fundamento de recusa o controlo de competência da autoridade de origem (alínea /a)/ do n.º 2 do artigo 23.º CH 1996).

Assim, em Portugal, o regime da CH 1996 é aplicável ao reconhecimento e execução de medidas de proteção tomadas por autoridades de um Estado Contratante da CH 1996 que não seja, simultaneamente, um Estado-Membro da União Europeia. Retomando o exemplo dado /supra/, o reconhecimento e execução em Portugal de uma medida de proteção de criança residente habitualmente em Marrocos, tomada por uma autoridade marroquina, deve ser efetuado segundo o regime da CH 1996.

** b) Objeto do reconhecimento e execução
Beneficiam do regime de reconhecimento e execução previsto na CH 1996 as "medidas tomadas pelas autoridades de um Estado Contratante" (art. 23.º). Convém, por isso, analisar os conceitos de /(i)/ medidas de proteção e de /(ii)/ autoridades de um Estado Contratante e a /(iii)/ delimitação temporal do regime. Os conceitos da CH 1996, atendendo ao seu objetivo de uniformização das regras em matéria de responsabilidade parental nos Estados Contratantes, devem ser interpretados autonomamente.

O conceito de medidas de proteção não é definido pela CH 1996 [cite:@lagarde1996, n.º 18]. O conceito é utilizado, desde logo, no âmbito de aplicação material da CH 1996, no qual se estabelece que a CH 1996 tem por objeto "Determinar qual o Estado cujas autoridades têm competência para tomar as /medidas orientadas à protecção da pessoa ou bens da criança/;" e "Assegurar o reconhecimento e a execução de /tais medidas de protecção/ em todos os Estados Contratantes;" (alíneas /a)/ e /d)/ do n.º 1 do artigo 1.º; itálicos aditados). O conceito é depois concretizado, através de uma enumeração exemplificativa (artigo 3.º) e de uma delimitação negativa (artigo 4.º). Da conjugação destes preceitos (para cujas anotações se remete) resulta que o conceito de medidas de proteção é um conceito /amplo/, que abrange qualquer medida que vise a proteção da pessoa ou bens da criança, exceto as excluídas no artigo 4.º da CH 1996 [cite:@lagarde1996, n.º 26;@silberman2006, pp. 398-399].

O conceito de autoridade também não é definido pela CH 1996, ao contrário do que sucede no Regulamento Bruxelas II /ter/ (considerando n.º 14 e ponto 1) do n.º 2 do artigo 2.º do Regulamento Bruxelas II /ter/). Pode inferir-se do n.º 1 do artigo 5.º da CH 1996, que o conceito abrange autoridades judiciais e autoridades administrativas [cite:@nygh1997, p. 346]. Neste sentido, recorda-se que as regras de reconhecimento e execução da CH 1996 assentam, no espírito das "convenções duplas", na uniformização das regras de competência internacional [cite:@lagarde1996, n.º 119;@nygh1997, p. 355;@nygh1998, p. 23] e que a CH 1996 permite o controlo de competência da autoridade de origem (cf. /infra/), ou seja, permite recusar o reconhecimento de medidas tomadas por autoridades que não sejam internacionalmente competentes ao abrigo das normas de competência internacional da CH 1996.

O regime de reconhecimento e execução previsto na CH 1996 não tem eficácia retroativa. Resulta do n.º 2 do artigo 53.º (para cuja anotação se remete) que só beneficiam deste regime as medidas tomadas em data posterior à entrada em vigor da CH 1996 no Estado Contratante onde as medidas foram tomadas /e/ no Estado Contratante requerido. Assim, e por exemplo, uma medida de proteção tomada, em 2 de junho de 2025, pelas autoridades da República de El Salvador (Estado Contratante da CH 1996) cujo reconhecimento seja pedido em Portugal, não beneficia do regime de reconhecimento e execução previsto na CH 1996 (apesar de este regime vigorar em Portugal desde 1 de agosto de 2011), pois a Convenção só entrou em vigor na República de El Salvador em 1 de julho de 2025.

* 2. Reconhecimento automático (n.º 1)
A CH 1996 consagra o princípio do reconhecimento automático, isto é, as medidas de proteção tomadas num Estado Contratante são reconhecidas nos restantes Estados Contratantes sem necessidade de qualquer processo prévio [cite:@lagarde1996, n.º 119; @hcchpermanentbureau2018, n.º 10.1]. Daqui decorre que os Estados Contratantes /não/ podem impor um processo prévio de reconhecimento das medidas de proteção tomadas noutros Estados Contratantes [cite:@hilbig-lugani2016, artigo 23.º, anot. 2]. Não obstante, a CH 1996 permite que qualquer parte interessada solicite, a título principal, às autoridades do Estado Contratante requerido o reconhecimento ou o não reconhecimento de uma medida de proteção tomada num outro Estado Contratante (cf. artigo 24.º e respetiva anotação). A consagração do princípio do reconhecimento automático parece ter por base uma ideia de confiança mútua, consubstanciada na unificação das regras de competência internacional e de conflitos de leis nos Estados Contratantes [cite:@lagarde1996, n.º 119; @hilbig-lugani2016, artigo 23.º, anot. 1].

No Relatório Explicativo afirma-se que para ser reconhecida a medida deve ser provada [cite:@lagarde1996, n.º 120]. A CH 1996 nada estabelece sobre a /prova/ da medida de proteção. Em casos normais, bastará a apresentação do documento escrito em que conste a medida de proteção. No contexto de medidas de proteção tomadas em casos urgentes, o Relatório Explicativo esclarece que a CH 1996 não exige a apresentação de um documento escrito, datado e assinado pela autoridade do Estado Contratante de origem para o reconhecimento da medida de proteção, indicando que, por exemplo, um telefax (ou, atualizando o exemplo, uma mensagem de correio eletrónico) pode ser prova suficiente de que uma medida de proteção foi tomada no Estado Contratante de origem para efeitos do seu reconhecimento [cite:@lagarde1996, n.º 120]. Entende-se que esta flexibilização da prova de que uma medida de proteção foi tomada é aplicável em qualquer caso e não apenas nos casos urgentes [cite:@hilbig-lugani2016, artigo 23.º, anot. 5].

A medida de proteção tomada no Estado Contratante de origem estará, muitas vezes, redigida em língua estrangeira. A CH 1996 nada estabelece sobre a necessidade ou desnecessidade de tradução da medida de proteção. Entende-se que esta questão deve ser resolvida pelo Direito processual do Estado Contratante requerido. No caso português, o Direito processual vigente não exige que a medida de proteção seja necessariamente acompanhada de uma tradução, nem estabelece, em regra, qualquer requisito específico referente à tradução [cite:cf. Ac. STJ 12/07/2011, proc. n.º 987/10.5YRLSB.S1, Paulo Sá e, no contexto do processo especial de revisão e confirmação de sentenças estrangeiras, @almeida2017c, pp. 599-600 e referências bibliográficas aí indicadas].

* 3. Fundamentos de recusa do reconhecimento (n.º 2)
** a) Aspetos gerais
O reconhecimento /pode/ ser recusado /se/ se verificar algum dos fundamentos enumerados no n.º 2 do artigo 23.º. Daqui resulta um regime com um pendor claramente favorável ao reconhecimento das medidas de proteção, uma vez que a enumeração dos fundamentos de recusa /é exaustiva/ e a verificação de um (ou mais) fundamentos de recusa /permite/ que a autoridade do Estado Contratante requerido recuse o reconhecimento, mas não o impõe [cite:cf. Ac. TRC 24/10/2023, proc. n.º 4/23.5YRCBR, Henrique Antunes; @lagarde1996, n.º 121; @ramos2002c pp. 119-120]. Deste modo, a recusa do reconhecimento, quando possível, é uma decisão descricionária da autoridade do Estado Contratante requerido [cite:/F v M [2018] EWHC 2106 (Fam)/, n.º 63, e @hilbig-lugani2016, artigo 23.º, anot. 7].

** b) Controlo da competência da autoridade do Estado Contratante de origem
O reconhecimento pode ser recusado se a medida de proteção foi tomada por uma autoridade que não tem competência internacional ao abrigo da CH 1996. Este fundamento de recusa permite à autoridade do Estado Contratante requerido controlar a competência da autoridade do Estado Contratante que tomou a medida de proteção, estando, porém, vinculada à matéria de facto (cf. artigo 25.º e respetiva anotação). O facto de não ter sido invocada a falta de competência internacional junto da autoridade de origem ou de a medida de proteção ter sido tomada sem oposição não impedem a verificação deste fundamento de recusa, mas podem ser tomados em consideração pela autoridade do Estado Contratante requerido na sua decisão de recusa ou não do reconhecimento [cite:@hilbig-lugani2016, artigo 23.º, anot. 12].

Para se verificar este fundamento de recusa /não/ basta que a autoridade do Estado Contratante de origem tenha fundado a sua competência internacional em /norma/ atributiva de competência internacional diversa das da CH 1996; é necessário que o /critério/ atributivo de competência internacional em que fundou a sua competência /não esteja/ previsto nas normas de competência internacional da CH 1996 [cite:cf., em sentido semelhante, @hilbig-lugani2016, artigo 23.º, anot. 14; @hcchpermanentbureau2018, n.º 10.5]. Isto é particularmente relevante no contexto da articulação com o Regulamento Bruxelas II /ter/. Veja-se o seguinte exemplo: os tribunais portugueses tomam uma medida de proteção relativa aos bens de uma criança residente habitualmente em Portugal. Essa criança tem bens em Marrocos. O reconhecimento da medida de proteção tomada pelos tribunais portugueses não deve ser recusado em Marrocos com base neste fundamento de recusa apenas porque os tribunais portugueses fundaram a sua competência internacional no artigo 7.º do Regulamento Bruxelas II /ter/. Apesar de a norma jurídica ser diferente, o critério atributivo da competência internacional (residência habitual da criança) está previsto no artigo 5.º da CH 1996 e, por isso, não se deve considerar verificado este fundamento de recusa.

Atendendo ao /favor recognitionis/ e à redação deste fundamento de recusa, entende-se que o mesmo /não/ está preenchido nos casos em que a autoridade do Estado Contratante de origem toma a medida de proteção em violação do disposto no artigo 13.º (para cuja anotação se remete), uma vez que, nestes casos, a autoridade do Estado Contratante é internacionalmente competente ao abrigo dos artigos 5.º a 10.º da CH 1996 [cite:/contra/ @hilbig-lugani2016, artigo 23.º, anot. 13].

** c) Não audição da criança
O reconhecimento pode ser recusado se a medida de proteção tiver sido tomada, salvo em casos de urgência, sem ter sido concedida à criança a oportunidade de ser ouvida, desde que tal viole os princípios fundamentais do Estado Contratante requerido. Este fundamento de recusa é inspirado pelo artigo 12.º da Convenção sobre os Direitos da Criança, no qual se estabelece que "Os Estados Partes garantem à criança com capacidade de discernimento o direito de exprimir
livremente a sua opinião sobre as questões que lhe respeitem, sendo devidamente tomadas em consideração as opiniões da criança, de acordo com a sua idade e maturidade" e que "é assegurada à criança a oportunidade de ser ouvida nos processos judiciais e administrativos que lhe respeitem, seja directamente, seja através de representante ou de organismo adequado, segundo as modalidades previstas pelas regras de processo da legislação nacional"  [cite:@lagarde1996, n.º 123]. O direito de a criança ser ouvida encontra-se também consagrado no n.º 1 do artigo 24.º da Carta dos Direitos Fundamentais da União Europeia.

No contexto da legislação europeia, a alínea /b)/ do artigo 23.º do Regulamento Bruxelas II /bis/ consagrava um fundamento de recusa substancialmente idêntico. Uma das alterações mais relevantes do Regulamento Bruxelas II /ter/ foi a ênfase dada ao direito da criança ser ouvida [cite:cf. o artigo 21.º deste Regulamento e @goncalves2022a pp. 64-66; @goncalves2023 pp. 137-143; @oliveira2022 pp. 47-49]. No regime "normal" de reconhecimento de decisões em matéria de responsabilidade parental, as exceções foram reconfiguradas, podendo não ser dada oportunidade à criança para se pronunciar se o processo tiver unicamente por objeto os bens da criança /e/ desde que não seja necessário dar essa oportunidade à luz do mérito da causa do processo /ou/ se houver motivos sérios tendo em conta, em especial, a urgência do processo (cf. alíneas /a)/ e /b)/ do n.º 2 do artigo 39.º e considerando n.º 57 do Regulamento Bruxelas II /ter/).

A CH 1996 não dispõe sobre o modo como a criança deve ser ouvida. Parece, assim, que a audição da criança por um modo que não esteja previsto no Direito do Estado requerido não é, por si só, suficiente para preencher este fundamento de recusa. De igual modo, o que é necessário é que seja dada real e efetiva oportunidade à criança para exprimir livremente a sua opinião. Daqui decorre que para o preenchimento deste fundamento de recusa não é decisivo que a criança não tenha sido ouvida; decisivo é que lhe tenha (ou não) sido concedida a oportunidade (real e efetiva) de ser ouvida.

Mesmo nos casos em que não tenha sido concedida à criança a oportunidade de ser ouvida, o fundamento de recusa só ficará preenchido quando tal viole os princípios fundamentais do Estado Contratante requerido (cf., neste sentido, /NG v OG [2014] EWHC 4182 (Fam)/, n.º 67 e ss.). Trata-se de uma cláusula especial de ordem pública internacional processual do Estado contratante requerido [cite:@lagarde1996, n.º 123]. Como tal, o Direito do Estado requerido desempenha um papel decisivo no preenchimento deste fundamento de recusa [cite:@hilbig-lugani2016, artigo 23.º, anot. 16].

Este fundamento de recusa não é aplicável quando a medida de proteção tenha sido tomada em caso de urgência. A CH 1996 não define o conceito, utilizando-o também no artigo 11.º (para cuja anotação se remete). Nessa sede, afirma-se que será urgente a situação em que exista o risco de danos irreparáveis para a criança [cite:@lagarde1996, n.º 68]. Pensa-se que se deve partir desta ideia, mas assinala-se que, no contexto deste fundamento de recusa, podem tomar medidas de proteção em casos urgentes quer as autoridades competentes nos termos do artigo 11.º da CH 1996, quer as autoridades competentes nos termos dos artigos 5.º a 10.º da CH 1996 [cite:@hilbig-lugani2016, artigo 23.º, anot. 17]. São avançados alguns exemplos de casos urgentes: /(i)/ a criança carece de tratamento médico para salvar a sua vida, não sendo possível obter, em tempo, consentimento dos progenitores; /(ii)/ a criança alega ser vítima de agressão física ou abuso sexual após contacto com um dos progenitores, sendo necessário suspender o contacto de imediato; /(iii)/ é necessário proceder rapidamente à venda de bens perecíveis da criança [cite:@hcchpermanentbureau2018, n.º 6.4].

** d) Não audição da pessoa com responsabilidades parentais
O reconhecimento pode ser recusado quando tenha sido tomada uma medida de proteção que afete as responsabilidade parentais de uma pessoa e não tenha sido concedida a essa pessoa a possibilidade de ser ouvida, salvo em casos de urgência. Trata-se, novamente, de uma cláusula especial de ordem pública internacional processual do Estado contratante requerido [cite:@lagarde1996, n.º 124], assente no princípio da tutela jurisdicional efetiva. O Regulamento Bruxelas II /ter/ consagra, na alínea /c)/ do n.º 1 do artigo 39.º, fundamento de recusa substancialmente similar.

Como resulta da redação do preceito, estamos perante um fundamento de recusa que não é de conhecimento oficioso. Este fundamento de recusa carece de ser alegado pela pessoa que considera que a medida de proteção tomada infringe as suas responsabilidades parentais [cite:@hilbig-lugani2016, artigo 23.º, anot. 18]. Assim, e por exemplo, se uma autoridade marroquina tomar uma medida de proteção, sem ser no contexto de um caso de urgência, que priva o progenitor masculino do exercício das suas responsabilidades parentais sem lhe dar oportunidade para ser ouvido, o reconhecimento dessa medida pode ser recusado pelas autoridades portuguesas, mas apenas se o progenitor masculino o invocar [cite:exemplo adaptado de @hcchpermanentbureau2018, exemplo 10 f)]. Em /Uhd v McKay [2019] EWHC 1239 (Fam)/, n.º 103, ponderou-se se não seria abuso de direto a invocação deste fundamento de recusa pelo progenitor que deslocou ilicitamente a criança para um outro Estado e procurou ocultar o seu paradeiro. O Tribunal acabou por não decidir, pois considerou que duas exceções destes fundamento de recusa se encontravam preenchidas: /(i)/ a medida de proteção foi tomada após e em resposta à deslocação ilícita da criança por um dos progenitores, o que foi considerado pelo Tribunal como um caso urgente; /(ii)/ o tribunal que tomou a medida de proteção concedeu ao progenitor que deslocou ilícitamente a criança a oportunidade de ser ouvido, tendo inclusive este sido representado por advogados no processo judicial em que as medidas foram tomadas.

Também este fundamento de recusa não é aplicável quando a medida de proteção tenha sido tomada em caso de urgência (remetendo-se para as observações efetuadas no contexto da preterição do direito de audição da criança).

** e) Violação da ordem pública internacional
A CH 1996 consagra o fundamento clássico de recusa do reconhecimento assente na contrariedade à ordem pública internacional do Estado Contratante requerido. A redação deste fundamento de recusa é muito próxima da adotada pela CH 1996 em sede determinação do Direito aplicável (cf. artigo 22.º e respetiva anotação) e pode ser dividida em duas partes: /(i)/ a primeira ("Se tal reconhecimento é manifestamente contrário à ordem pública do Estado requerido") corresponde à formulação tradicional adotada em sede da Conferencia da Haia e acentua a característica da excecionalidade da ordem pública internacional; /(ii)/ a segunda ("tendo em conta os melhores interesses da criança") estabelece a necessidade de tomar em consideração o princípio do superior interesse da criança no momento da avaliação. Este aditamento à formulação clássica da Conferência da Haia surgiu no artigo 24.º da Convenção da Haia de 1993 Relativa à Protecção das Crianças e à Cooperação em Matéria de Adopção Internacional e foi posteriormente adotado também no contexto da legislação europeia, encontrando-se atualmente previsto na alínea /a)/ do n.º 1 do artigo 39.º do Regulamento Bruxelas II /ter/.

A característica da excecionalidade deduz-se da formulação tradicional que estabelece a possibilidade de recusar o reconhecimento da medida de proteção se este for "manifestamente contrário à ordem pública do Estado requerido". Subjacente à consagração expressa da contrariedade manifesta está a ideia de que os órgãos aplicadores do direito devem exercer particular restrição na utilização deste fundamento de recusa (cf., neste sentido, /Uhd v McKay [2019] EWHC 1239 (Fam)/, n.º 78). Compreende-se o acentuar desta característica porque a adoção de uma conceção ampla e consequente recurso frequente e ou excessivo à ordem pública internacional coloca em crise os objetivos prosseguidos pela CH 1996.

A autoridade deve, na análise deste fundamento de recusa, tomar em consideração os melhores interesses da criança. A articulação entre a contrariedade manifesta aos princípios fundamentais da ordem pública internacional do Estado Contratante requerido e o superior interesse da criança deve ser ponderada. No contexto do artigo 24.º da Convenção da Haia de 1993 Relativa à Protecção das Crianças e à Cooperação em Matéria de Adopção Internacional equacionaram-se e rejeitaram-se formulações que apontavam para a necessidade de preenchimento cumulativo dos dois elementos para que se pudesse recusar o reconhecimento de uma adoção [cite:@parra-aranguren2022, n.ºs 424-426]. Em sede do artigo 22.º da CH 1996, sustenta-se que o princípio do superior interesse da criança deve inspirar a aplicação de todos os artigos da CH 1996 [cite:@lagarde1996, n.º 117]. Parece claro que o princípio do superior interesse da criança pode atuar como limite a este fundamento de recusa [cite:@silberman2006 pp. 421-422], isto é, o reconhecimento de uma medida de proteção é manifestamente contrário a ordem pública internacional do Estado Contratante requerido, mas a recusa do reconhecimento seria contrária ao superior interesse da criança (veja-se o exemplo dado no Ac. TRC 24/10/2023, proc. n.º 4/23.5YRCBR, Henrique Antunes: "Assim, v.g., ainda que a atribuição, pela Estado de origem, das responsabilidades parentais a um dos pais assente comprovadamente numa discriminação inaceitável do outro, a decisão estrangeira deve, ainda assim, ser reconhecida se essa atribuição corresponder ao interesse superior da criança."). Em casos como este, a autoridade pode decidir não recusar o reconhecimento. Suscita mais dúvidas a possibilidade de acionar este fundamento de recusa não porque o reconhecimento da medida de proteção contrarie manifestamente princípios fundamentais da ordem pública internacional do Estado requerido, mas porque a autoridade do Estado requerido considera que a mesma terá impactos adversos na criança [cite:cf., suscitando esta hipótese, @nygh1998 p. 24].

Indiretamente, a tomada em consideração do princípio do superior interesse da criança acentua o carácter aposteriostíco da ordem pública internacional. Ou seja, não é possível efetuar uma análise /in abstracto/ da contrariedade manifesta à ordem pública internacional nem do princípio do superior interesse da criança. A autoridade do Estado requerido deve efetuar um juízo /in concreto/, atendendo a todas as circunstância do caso. A avaliação da conformidade do reconhecimento da medida de proteção com a ordem pública internacional do Estado Contratante requerido constitui tarefa que só pode ser efetuada no caso concreto.

A ordem pública internacional relevante é a do Estado Contratante requerido. Como tal, o conteúdo da ordem pública internacional pode ser, e em princípio será, diferente consoante o Estado Contratante em que seja necessário o reconhecimento da medida de proteção. A ordem pública internacional tem, assim, carácter nacional [cite:cf., em geral e por todos, @oliveira2011 p. 625; @oliveira2024 p. 354; @pinheiro2025 pp. 624-627; @ramos2002; @vicente2020 pp. 155-156].

** f) Incompatibilidade de medidas de proteção
O reconhecimento de uma medida de proteção pode ser recusado se esta for incompatível com uma medida de proteção /posterior/ tomada no Estado /não Contratante/ da /residência habitual da criança/, desde que esta última medida reúna as condições para ser reconhecida no Estado Contratante requerido. Este fundamento de recusa foi igualmente consagrado na alínea /e)/ do n.º 1 do artigo 39.º do Regulamento Bruxelas II /ter/ (que o estende às decisões posteriores tomadas noutros Estados-Membros).

Este fundamento de recusa assenta nas ideias de incompatibilidade das medidas de proteção e de que, em matéria de responsabilidade parental, a medida de proteção posterior deve prevalecer pois reflete melhor a situação atual da criança e, por isso, corresponderá melhor ao seus superiores interesses. O fundamento de recusa abrange apenas as medidas de proteção posteriores tomadas pelo Estado não Contratante da residência habitual da criança. A limitação ao Estado da residência habitual da criança compreende-se, porque este será - no contexto da CH 1996 - o Estado que tem maior proximidade com a criança e, como tal, o melhor colocado para avaliar o superior interesse da criança [cite:@lagarde1996, n.º 131;@hilbig-lugani2016, artigo 23.º, anot. 25]. Suscita maiores reservas a limitação deste fundamento a Estados não Contratantes. A letra deste preceito aponta no sentido de que uma medida de proteção posterior, tomada pelas autoridades do Estado Contratante da residência habitual da criança, não seria fundamento para recusar o reconhecimento de uma medida de proteção anterior, tomada pelas autoridades de um outro Estado Contratante. Esta interpretação não parece ser a melhor, por várias ordens de razão: /(i)/ coloca em melhor posição as medidas tomadas por um Estado não contratante; /(ii)/ contraria a relevância dada pela CH 1996 à residência habitual na determinação do tribunal internacionalmente competente e da lei aplicável; /(iii)/ faria divergir o regime de reconhecimento do regime expressamente consagrado no artigo 14.º da CH 1996 (para cuja anotação se remete), no qual se estabelece que as autoridades dos Estados Contratantes internacionalmente competentes ao abrigo dos artigos 5.º a 10.º têm competência para modificar, substituir ou anular medidas. Observando o sistema da CH 1996, parece que o conflito entre medidas de proteção tomadas por Estados Contratantes deve ser resolvido dando prevalência à medida posterior [cite:cf., em sentido semelhante, @hilbig-lugani2016, artigo 23.º, anot. 27;@benicke2013 p. 51; @nygh1998 p. 24].

A medida de proteção posterior, tomada pelo Estado não contratante da residência habitual da criança só pode fundamentar a recusa de reconhecimento se reunir as condições para ser ela própria reconhecida no Estado Contratante requerido. Como a medida de proteção foi tomada pelas autoridades de um Estado não Contratante, não são aplicáveis as regras de reconhecimento da CH 1996, antes sendo aplicável um outro regime de reconhecimento vigente no Estado Contratante requerido. Quando a questão se coloque em Portugal, o reconhecimento da medida de proteção tomada no Estado não Contratante seguirá, em regra, os termos do processo especial de revisão e confirmação (artigos 978.º e ss. do CPC).

** g) Preterição dos procedimentos previstos no artigo 33.º
O artigo 33.º da CH 1996 (para cuja anotação se remete) prevê um procedimento de consulta obrigatório nos casos de colocação ou acolhimento transfronteiriço de crianças noutro Estado Contratante. Nos casos em que a autoridade de um Estado Contratante decida a colocação ou acolhimento transfronteiriço da criança, preterindo esse procedimento de consulta, os outros Estados Contratantes (em particular o Estado Contratante que não foi consultado) podem recusar o reconhecimento da medida. O Regulamento Bruxelas II /ter/ consagra um fundamento de recusa substancialmente similar (alínea /f)/ do n.º 1 do artigo 39.º). Segundo o Relatório Explicativo, este fundamento de recusa visa, primariamente, evitar que o Estado Contratante que não foi consultado (quando deveria ter sido) seja colocado numa situação de facto consumado [cite:@lagarde1996, n.º 127].

* 4. Bibliografia
#+print_bibliography:

* 5. Jurisprudência
Ac. STJ 12/07/2011, proc. n.º 987/10.5YRLSB.S1, Paulo Sá.

/NG v OG [2014] EWHC 4182 (Fam)/, disponível em https://www.bailii.org/ew/cases/EWHC/Fam/2014/4182.html e consultado pela última vez em 24 de junho de 2025.

/F v M [2018] EWHC 2106 (Fam)/, disponível em https://www.bailii.org/ew/cases/EWHC/Fam/2018/2106.html e consultado pela última vez em 24 de junho de 2025.

/Uhd v McKay [2019] EWHC 1239 (Fam)/, disponível em https://www.bailii.org/ew/cases/EWHC/Fam/2019/1239.html e consultado pela última vez em 24 de junho de 2025.

Ac. TRC 24/10/2023, proc. n.º 4/23.5YRCBR, Henrique Antunes.

* Footnotes

[fn:1] Cf. artigo 2.º da Decisão 2003/93/CE do Conselho, de 19 de dezembro de 2002, que autoriza os Estados-Membros a assinarem, no interesse da Comunidade, a Convenção da Haia de 1996 relativa à jurisdição, à lei aplicável, ao reconhecimento, à execução e à cooperação em matéria de responsabilidade parental e de medidas de proteção dos filhos (JO L 48 de 21.2.2003) e artigo 2.º da Decisão 2008/431/CE do Conselho, de 5 de junho de 2008, que autoriza certos Estados-Membros a ratificar ou aderir, no interesse da Comunidade Europeia, à Convenção da Haia de 1996 relativa à competência, à lei aplicável, ao reconhecimento, à execução e à cooperação em matéria de responsabilidade parental e de medidas de proteção da criança, e que autoriza certos Estados-Membros a fazer uma declaração sobre a aplicação da regulamentação interna pertinente do direito comunitário — Convenção relativa à competência, à lei aplicável, ao reconhecimento, à execução e à cooperação em matéria de responsabilidade parental e de medidas de proteção da criança (JO L 151 de 11.6.2008).
