#+title: Anotação ao artigo 28.º da CH1996
#+author: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil author:nil date:nil title:nil

#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{titletoc}
#+LATEX_HEADER: \KOMAoptions{headings=small}

#+bibliography: ~/Dropbox/Bibliografia/BetterBibLatex/bib.bib
#+cite_export: csl np405.csl

#+begin_quote

#+begin_center
*Artigo 28.º*
#+end_center

As medidas tomadas num Estado Contratante, declaradas executórias, ou registadas para fins de execução num outro Estado Contratante, serão executadas nesse último Estado Contratante como se tivessem sido tomadas pelas autoridades desse Estado. A execução das medidas far-se-á em conformidade com a lei do Estado requerido nos termos previstos pela respectiva lei, tomando em consideração os melhores interesses da criança.

#+end_quote

*Sumário:* 1. Introdução; 2. Equiparação à execução das medidas de proteção nacionais; 3. A execução e o superior interesse da criança; 4. Bibliografia; 5. Jurisprudência.

* 1. Introdução
O artigo 26.º contém as regras da CH 1996 sobre o processo de atribuição de força executória (/exequatur/) a medidas de proteção tomadas noutro Estado Contratante. O artigo 28.º contém as regras da CH 1996 sobre a (efetiva) execução no Estado Contratante requerido de medidas de proteção tomadas noutro Estado Contratante. Deste modo, a relação entre estes dois preceitos é a seguinte: uma medida de proteção tomada num Estado Contratante não pode ser executada noutro Estado Contratante, sem que a medida seja previamente declarada executória ou registada nesse outro Estado Contratante.

Esta divisão entre atribuição de força executória (/exequatur/) e execução é comum às convenções da Conferência da Haia [cite:cf., por exemplo, artigos 25.º e 27.º da Convenção da Haia de 2000 relativa à Proteção Internacional de Adultos, artigo 14.º da Convenção da Haia de 2005 sobre Acordos de Eleição do Foro, artigo 13.º da Convenção da Haia de 2019 sobre o Reconhecimento e a Execução de Sentenças Estrangeiras em Matéria Civil ou Comercial e @garcimartin2020a, n.º 309], à Convenção de Bruxelas (cf. Acórdão do Tribunal de Justiça de 2 de julho de 1985, /Deutsche Genossenschaftsbank contra SA Brasserie du Pêcheur/, 148/84, EU:C:1985:280, n.º 18, no qual se afirma que a Convenção se limita a regular o processo de /exequatur/ e não versa sobre a execução propriamente dita, que permanece submetida ao Direito do Estado requerido) e, apesar da supressão do /exequatur/, ao Regulamento Bruxelas I /bis/ [cite:cf. artigo 41.º e @magnus2023, artigo 41.º, anots. 1-2] e ao Regulamento Bruxelas II /ter/ [cite:cf. artigo 51.º e @goncalves2023 pp. 227-229; @magnus2023a, artigo 51.º, anots. 1-3].

* 2. Equiparação à execução das medidas de proteção nacionais
O artigo 28.º da CH 1996 consagra a teoria da equiparação: obtida a declaração de executoriedade, a medida de proteção tomada no Estado Contratante de origem deve ser executada no Estado Contratante requerido da mesma maneira que são executadas as medidas de proteção tomadas pelas autoridades deste Estado [cite:@lagarde1996, n.º 134, fala de uma espécie de "naturalização" da medida no Estado Contratante requerido]. Não podem, por isso, ser criadas normas jurídicas que estabeleçam um regime diferente (em regra, mais restritivo ou gravoso) de execução das medidas de proteção tomadas por Estados Contratantes da CH 1996 do que o existente para a execução das medidas de proteção nacionais [cite:cf., em sentido semelhante, @hilbig-lugani2016, artigo 28.º, anot. 1]. E a execução pode ser recusada com base nos mesmos fundamentos de recusa de execução de medidas de proteção nacionais [cite:@benicke2013 p. 51].

Este tratamento igual parece ter por base a ideia de que as questões que podem surgir na fase da execução de medidas de proteção em situações transnacionais podem igualmente surgir na fase de execução de medidas de proteção em situações puramente internas, devendo por isso ser resolvidas do mesmo modo. O Relatório Explicativo dá o exemplo da execução de uma medida de proteção que fixou a residência de uma criança com um certo grau de maturidade com um dos progenitores, sendo que a criança se recusa em absoluto a ir viver com esse progenitor [cite:@lagarde1996, n.º 134].

Desta ideia de tratamento igual decorre, igualmente, que a execução é regulada pela lei do Estado Contratante requerido. De qualquer modo, a primeira parte do segundo período do artigo 28.º da CH 1996 ("A execução das medidas far-se-á em conformidade com a lei do Estado requerido nos termos previstos pela respectiva lei") explicita isso mesmo. Retomando o exemplo acima mencionado, se a oposição da criança à execução da medida constituir um fundamento de recusa da execução no Direito nacional do Estado Contratante requerido, então a execução da medida de proteção tomada no Estado Contratante de origem pode ser recusada com base nessa oposição. Por outro lado, a medida de proteção tomada no Estado Contratante de origem só poderá ser executada se a sua execução for permitida nos termos da lei do Estado Contratante requerido. Neste ponto, o Relatório Explicativo dá o exemplo de uma medida de proteção, tomada no Estado Contratante da residência habitual da criança, que mantém a criança com a família, mas sob supervisão de uma autoridade administrativa local. A família muda a residência habitual para outro Estado Contratante. A medida só pode ser executada no Estado Contratante da nova residência habitual se as suas autoridades forem competentes, ao abrigo da /lex fori/, para efetuarem a supervisão da família, tal como prevista na medida de proteção do Estado Contratante da anterior residência habitual [cite:@lagarde1996, n.º 135]. Um outro exemplo é a proibição de coerção direta contra a criança (cf. § 90 (2) /IntFamRVG/). Assim, e por exemplo, uma medida de proteção em matéria de visita não será executada na Alemanha se carecer de coerção direta sobre a criança.

* 3. A execução e o superior interesse da criança
O segundo período do artigo 28.º da CH 1996, na sua parte final, indica que a execução deve ser efetuada "tomando em consideração os melhores interesses da criança". Este aditamento suscitou críticas, por se admitir que poderia ser utilizado pelas autoridades do Estado Contratante requerido para introduzir, na fase de execução, um novo exame do mérito da medida de proteção [cite:@silberman2006 p. 421]. Afirma-se, talvez em reação, que esta referência aos melhores interesses da criança "não deve ser interpretada como um convite a mais inquirições quanto ao mérito" [cite:@hcchpermanentbureau2018, n.º 10.27]. Em contraponto, salienta-se que a referência aos melhores interesses da criança não é redundante porque a fase de execução é regulada pela lei do Estado Contratante requerido (e não pelas normas uniformes da CH 1996); porém, essa referência será mais útil nos casos em que o Estado Contratante requerido não tenha consagração similar nas suas normas que regulam a execução. Nesses casos corre-se, porém, o risco de um tratamento desigual: a execução da medida de proteção transnacional deverá ser efetuada segundo a lei do Estado Contratante requerido, tomando em consideração os melhores interesses da criança; a execução das medidas de proteção relativas a situções puramente deverá ser efetuada apenas segundo a /lex fori/ [cite:@hilbig-lugani2016, artigo 28, anot. 4].

* 4. Bibliografia
#+print_bibliography:

* 5. Jurisprudência
Acórdão do Tribunal de Justiça de 2 de julho de 1985, /Deutsche Genossenschaftsbank contra SA Brasserie du Pêcheur/, 148/84, EU:C:1985:280.
