#+title: Anotação ao artigo 27.º da CH1996
#+author: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil author:nil date:nil title:nil

#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{titletoc}
#+LATEX_HEADER: \KOMAoptions{headings=small}

#+bibliography: ~/Dropbox/Bibliografia/BetterBibLatex/bib.bib
#+cite_export: csl np405.csl

#+begin_quote

#+begin_center
*Artigo 27.º*
#+end_center

Sem prejuízo da análise que seja necessária para a aplicação dos artigos precedentes, não haverá qualquer revisão quanto ao mérito da medida tomada.

#+end_quote

*Sumário:* 1. Introdução; 2. Proibição de controlo do mérito; 3. Bibliografia; 4. Jurisprudência.

* 1. Introdução
A CH 1996 proíbe que o tribunal do Estado Contratante requerido proceda ao controlo do mérito da sentença, solução que é já tradicional nas convenções da Conferência da Haia que versam sobre o reconhecimento e execução [cite:cf. artigo 6.º da Convenção da Haia de 1970 sobre o Reconhecimento dos Divórcios e Separações de Pessoas, artigo 8.º da Convenção da Haia de 1971 sobre o Reconhecimento e a Execução de Sentenças Estrangeiras em Matéria Civil e Comercial, artigo 12.º da Convenção da Haia de 1973 sobre o Reconhecimento e Execução das Sentenças Relativas a Obrigações Alimentares, artigo 26.º da Convenção da Haia de 2000 relativa à Proteção Internacional de Adultos, artigo 8.º da Convenção da Haia de 2005 sobre Acordos de Eleição do Foro, n.º 2 do artigo 4.º da Convenção da Haia de 2019 sobre o Reconhecimento e a Execução de Sentenças Estrangeiras em Matéria Civil ou Comercial e @lagarde1996, n.º 133, que a considera uma cláusula típica das convenções sobre reconhecimento e execução].

No contexto europeu, a proibição de controlo do mérito foi consagrada na Convenção de Bruxelas [cite:cf. artigo 29.º e @jenard1990 p. 163] e, desde então, nos regulamentos da União Europeia que versam sobre o reconhecimento e execução, como o Regulamento Bruxelas I /bis/ [cite:cf. artigo 52.º e @gaudemet-tallon2018 pp. 589-592] e o Regulamento Bruxelas II /ter/ [cite:cf. artigos 70.º e 71.º e @almeida2022a pp. 110-111].

A proibição de controlo do mérito tem sido considerada essencial para a eficácia de qualquer instrumento internacional em matéria de reconhecimento e execução [cite:cf., em sede da Convenção da Haia de 2019 sobre o Reconhecimento e a Execução de Sentenças Estrangeiras em Matéria Civil ou Comercial, @garcimartin2020a, para. 119; e, no contexto da Convenção de Bruxelas e do Regulamento Bruxelas I /bis/, @jenard1990 p. 163; @mendes2022a p. 39;@magnus2023, artigo 52.º, anot. 1]. A proibição da /révision au fond/ é crucial para facilitar a "circulação" das medidas de proteção entre os Estados Contratantes da CH 1996 e encontra fundamento na ideia de confiança mútua (Ac. TRC 24/10/2023, proc. n.º 4/23.5YRCBR, Henrique Antunes) entre Estados Contratantes, que, no caso da CH 1996, assenta na uniformização das normas de determinação da competência internacional e de direito de conflitos.

* 2. Proibição de controlo do mérito
O controlo do mérito encontra-se vedado, seja na vertente fraca, em que se controla apenas a lei aplicada, seja na vertente forte, em que se controla também se a lei foi corretamente interpretada e aplicada [cite:@pinheiro2019a p. 70]. Ou seja, em regra, a autoridade do Estado Contratante requerido não pode verificar se a autoridade que tomou a medida de proteção no Estado Contratante de origem determinou a lei aplicável em conformidade com as normas uniformes da CH 1996, se interpretou e aplicou corretamente ao caso concreto a lei aplicável, nem se valorou corretamente a matéria de facto. Assim, e por exemplo, a autoridade do Estado Contratante requerido não pode questionar a validade ou correção da medida de proteção tomada no Estado Contratante de origem, nem, consequentemente, pode recusar o reconhecimento ou declaração de executoriedade porque teria aplicado lei diferente, porque teria tomado diferente medida de proteção ou a medida de proteção tomada seria inadmissível ou desconhecida do direito material que aplicaria ou porque considera que alguma questão de facto ou de direito foi incorretamente apreciada pela autoridade do Estado Contratante de origem.

Apesar de o limite se referir expressamente ao controlo do mérito da medida de proteção tomada, resulta - pelo menos de uma leitura conjugada dos artigos 23.º e 27.º da CH 1996 - que também se encontra vedada a reapreciação de questões processuais subjacentes à medida de proteção. Neste sentido aponta a ideia de confiança mútua, a importância de promover a circulação célere de medidas de proteção de crianças e o elenco exaustivo de fundamentos de recusa do reconhecimento ou declaração de executoriedade.

Estabelece-se, no entanto, que é permitida a análise do mérito na medida em que seja necessária para a aplicação dos artigos precedentes. Alguns dos fundamentos de recusa elencados no artigo 23.º carecem, para serem aplicados, da análise pela autoridade do Estado Contratante requerido da matéria de facto e de direito subjacente à medida de proteção tomada pela autoridade do Estado Contratante de origem. É o caso do controlo de competência da autoridade do Estado Contratante de origem (cf. alínea /a)/ do artigo 23.º da CH 1996 e 3.b) da anotação respetiva). Recorda-se que, quanto a este fundamento, a possibilidade de análise está limitada pela vinculação da autoridade do Estado Contratante requerido à matéria de facto em que a autoridade do Estado Contratante de origem baseou a sua competência (cf. artigo 25.º e respetiva anotação). A autoridade do Estado Contratante requerido pode igualmente analisar a medida para verificar se o reconhecimento e execução da mesma não é manifestamente contrário à sua ordem pública (processual e substantiva) internacional (cf. alíneas /b)/ e /d)/ do artigo 23.º da CH 1996 e 3.c) e e) da anotação respetiva). Considera-se que a verificação da não violação de princípios fundamentais da ordem pública (processual e substantiva) internacional do Estado Contratante requerido permite atender aos fundamentos e tramitação processual da medida. Ainda assim, esta possibilidade encontra-se limitada pelo carácter excecional da ordem pública internacional (cf. /Uhd v McKay [2019] EWHC 1239 (Fam)/, n.º 78, e /E v The Child and Family Agency of Ireland & Ors [2024] EWHC 1778 (Fam)/ n.ºs 12, 13 e 27).

No contexto do reconhecimento e /exequatur/ de uma medida de proteção, a autoridade do Estado Contratante requerido não pode alterar, substituir ou anular a medida. Porém, em certos casos, a autoridade do Estado Contratante requerido pode ser igualmente internacionalmente competente ao abrigo da CH 1996 e, como tal, ter competência para alterar, substituir ou anular a medida de proteção (cf. artigo 14.º da CH 1996 e anotação respetiva). É o caso, por exemplo, quando há uma mudança de residência habitual da criança (cf., dando o mesmo exemplo, Ac. TRC 24/10/2023, proc. n.º 4/23.5YRCBR, Henrique Antunes). Imagine-se o seguinte caso: a mãe pretende mudar-se da Suíça para Portugal com os filhos. O pai não dá o seu acordo à mudança, mas a mãe é autorizada a efetuar a mudança pela autoridade suíça, que estabelece um regime de contacto entre o pai e os filhos. O pai muda também a sua residência habitual para Portugal para manter contacto com os filhos [cite:exemplo adaptado de @hcchpermanentbureau2018 exemplo 8 c)]. Esta medida de proteção é reconhecida automaticamente em Portugal e, se não for cumprida, o pai pode pedir a declaração de executoridade da mesma (artigos 23.º e 26.º da CH 1996). Porém, a partir do momento em que a residência habitual da criança se fixou em Portugal, os tribunais portugueses têm, ao abrigo do artigo 14.º da CH 1996, competência internacional para alterar, substituir ou anular aquela medida de proteção e é a lei portuguesa (cf. n.º 3 do artigo 15.º da CH 1996) que determinará as condições de aplicação daquela medida.

* 3. Bibliografia
#+print_bibliography:

* 4. Jurisprudência
/Uhd v McKay [2019] EWHC 1239 (Fam)/, disponível em https://www.bailii.org/ew/cases/EWHC/Fam/2019/1239.html e consultado pela última vez em 24 de junho de 2025.

Ac. TRC 24/10/2023, proc. n.º 4/23.5YRCBR, Henrique Antunes.

/E v The Child and Family Agency of Ireland & Ors [2024] EWHC 1778 (Fam)/, disponível em https://www.bailii.org/ew/cases/EWHC/Fam/2024/1778.html e consultado pela última vez em 24 de junho de 2025.
