#+title: Anotação artigo 23.º da CH1996
#+author: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil author:nil date:nil title:nil

#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{titletoc}
#+LATEX_HEADER: \KOMAoptions{headings=small}

#+bibliography: ~/Dropbox/Bibliografia/BetterBibLatex/bib.bib
#+cite_export: csl np405.csl

#+begin_quote

Artigo 23.º

1. As medidas tomadas pelas autoridades de um Estado Contratante serão reconhecidas por força de lei em todos os outros Estado Contratantes.

2. Todavia, o reconhecimento poderá ser recusado:

  a) Se a medida tiver sido tomada por uma autoridade cuja competência não assenta em nenhum dos fundamentos previstos no capítulo II;

  b) Se a medida tiver sido tomada, salvo em caso de urgência, num contexto de um processo judiciário ou administrativo, sem se ter concedido à criança a possibilidade de ser ouvida, violando os princípios fundamentais dos procedimentos do Estado requerido;

  c) Se qualquer pessoa apresentar pedido indicando que a medida infringe as suas responsabilidades parentais, se tal medida ter sido tomada, salvo em casos de urgência, sem se ter concedido a essa pessoa a possibilidade de ser ouvida;

  d) Se tal reconhecimento é manifestamente contrário à ordem pública do Estado requerido, tendo em conta os melhores interesses da criança;

  e) Se a medida for incompatível com outra medida posterior tomada no Estado não Contratante da residência habitual da criança, quando esta última medida preencha os requisitos necessários ao reconhecimento no Estado requerido;

  f) Se os procedimentos previstos no artigo 33.º não tiverem sido respeitados.

#+end_quote

*Sumário:*

* 1. Breves notas gerais sobre o Capítulo IV
** a) Articulação com o regime de reconhecimento e execução do Regulamento Bruxelas II /ter/
A CH 1996 regula a competência, a lei aplicável, o reconhecimento (sem sentido amplo) e a cooperação em matéria de responsabilidade parental e medidas
de protecção das crianças. O Regulamento Bruxelas II /ter/ regula a competência e o reconhecimento (em sentido amplo) em matéria matrimonial e em
matéria de responsabilidade parental, bem como o rapto internacional de crianças. Há, por isso, uma coincidência parcial de matérias reguladas por estes dois instrumentos. Ambos regulam a competência e o reconhecimento (em sentido amplo) em matéria de responsabilidade parental. O conceito de responsabilidade parental adotado pelo Regulamento Bruxelas II /ter/ é inspirado no consagado pela CH 1996[cite:@almeida2022 pp. 21-22;@magnus2023a pp.86-87;@gomes2023 pp. 1561-1562].

A articulação entre estes dois instrumentos efetua-se atendendo ao artigoo 52.º da CH 1996 (para cuja anotação se remete) e ao artigo 97.º do Regulamento Bruxelas II /ter/.

Do meu artigo sobre o âmbito de aplicação
A articulação com a Convenção da Haia de 1996 encontra-se prevista no artigo 97.º do Regulamento Bruxelas II ter. Estabelece-se que as regras de reconhecimento e execução do Regulamento Bruxelas II ter prevalecem sempre sobre as da Convenção da Haia de 1996, quando o Estado de origem e o Estado de reconhecimento sejam Estados-Membros da União Europeia vinculados ao Regulamento Bruxelas II ter 90. Esta solução — que parece visar uma mais fácil “circulação” das decisões no espaço europeu, assente no princípio da confiança mútua — acarreta, nos casos em que a criança tenha residência habitual num Estado terceiro que é um Estado contratante da Convenção da Haia de 1996, um risco de se reconhecerem decisões, ao abrigo do regime do Regulamento Bruxelas II ter, cujo reconhecimento poderia ser recusado ao abrigo do regime da Convenção da Haia de 1996 91.

** b) Articulação com outros instrumentos supraestaduais
** b) Objeto do reconhecimento e execução
*** aa) medidas de proteção
*** bb) tomadas pelas autoridades de um Estado Contratante
*** cc) delimitação temporal (art. 53.º)
* 2. Reconhecimento automático (n.º 1)
* 3. Fundamentos de recusa do reconhecimento (n.º 2)
** a) Aspetos gerais
*** aa) Enumeração exaustiva dos fundamentos de recusa
*** bb) Possibilidade, não obrigatoriedade, de recusa
** b) Controlo da competência da autoridade de origem
** c) Audição da criança
** d) Audição da pessoa com responsabilidades parentais
** e) Ordem pública internacional
** f) Incompatibilidade de medidas de proteção
** g) Preterição dos procedimentos previstos no artigo 33.º
* 4. Bibliografia
#+print_bibliography:

* 5. Lista de jurisprudência
