#+title: Anotação ao artigo 26.º da CH1996
#+author: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil author:nil date:nil title:nil

#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{titletoc}
#+LATEX_HEADER: \KOMAoptions{headings=small}

#+bibliography: ~/Dropbox/Bibliografia/BetterBibLatex/bib.bib
#+cite_export: csl np405.csl

#+begin_quote

#+begin_center
*Artigo 26.º*
#+end_center

1. Se as medidas tomadas num Estado Contratante e postas em vigor ali carecerem de execução num outro Estado Contratante, deverão, a pedido da parte interessada, ser declaradas executórias ou registadas com a finalidade de serem executadas nesse outro Estado, de acordo com o procedimento previsto pela lei desse último Estado.

2. Cada Estado Contratante aplicará um procedimento simples e rápido à declaração de exequatur ou registo.

3. A declaração de exequatur ou registo apenas poderá ser recusada com fundamento em um dos motivos previstos no artigo 23.º, n.º 2.

#+end_quote

*Sumário:*

* 1. Introdução
As medidas de proteção tomadas num Estado Contratante podem carecer, ou não, de serem executadas noutro Estado Contratante. Se não carecem de ser executadas (/v.g./, a atribuição de poderes de administração do património da criança a uma pessoa) bastará o reconhecimento da medida de proteção. Se a medida de proteção carecer de ser executada noutro Estado Contratante (/v.g./, venda executiva de bem da criança ou acolhimento institucional da criança), então é necessário iniciar previamente o processo de declaração de executoriedade ou, nalguns Estados Contratantes, o registo da medida de proteção [cite:@lagarde1996, para. 132; @hilbig-lugani2016, artigo 26.º, para. 1].

A CH 1996 remete a regulação do processo de declaração de executoriedade ou registo das medidas de proteção para o Direito de cada Estado Contratante, concentrando as poucas regras uniformes que estabelece no seu artigo 26.º. Esta opção legislativa foi também utilizada no artigo 25.º da Convenção da Haia de 2000 relativa à Proteção Internacional de Adultos [cite:cf., sobre esta Convenção, @lagarde2017;@ribeiro2011;@ribeiro2022]. No contexto europeu, assinala-se que o Regulamento Bruxelas II /ter/ suprimiu o /exequatur/, pelo que as decisões proferidas num Estado-Membro em matéria de responsabilidade parental, que aí tenham força executória,
são executórias nos outros Estados-Membros sem que seja necessária qualquer declaração de executoriedade (n.º 1 do artigo 34.º), mantendo-se regras para o processo de recusa da execução (artigo 59.º e ss.).

* 2. Declaração de executoriedade ou registo da medida de proteção (n.º 1)
** a) Aspetos gerais
Resulta do n.º 1 que para que uma medida de proteção tomada no Estado Contratante de origem seja executada no Estado Contratante requerido, há que previamente obter a declaração de executoriedade ou o registo da medida de proteção. Cabe ao Estado Contratante requerido estabelecer se a executoriedade da medida de proteção depende de um processo prévio de declaração de executoriedade ou do prévio registo da medida. Assim, em Inglaterra, a executoriedade depende do prévio registo da medida de execução, nos termos das /Family Procedure Rules 2010/, parte 31. Em Portugal, a executoriedade depende do processo prévio de declaração de executoriedade.

Para que uma medida de proteção possa ser declarada executória ou registada no Estado Contratante requerido, a CH 1996 estabelece os seguintes requisitos: /(i)/ a medida de proteção tem de ter força executória no Estado Contratante de origem; /(ii)/ a medida de proteção tem de carecer de execução no Estado Contratante requerido; /(iii)/ tem de ser pedida a declaração de executoriedade ou o registo por uma parte interessada.

** b) Força executória no Estado Contratante de origem
Só pode ser pedida a declaração de executoriedade ou o registo de medidas de proteção que tenham força executória no Estado Contratante em que foram tomadas. Tal solução compreende-se à luz da ideia de que a medida de proteção não deve produzir efeitos no Estado Contratante requerido que não lhe são atribuídos no país de origem [cite:cf., no contexto da Convenção de Bruxelas e dos regulamentos da União Europeia, @jenard1979 p. 48;@pinheiro2019a p. 89;@magnus2023a, artigo 34.º, para. 6].

A CH 1996 nada mais estabelece sobre a matéria. Parece, por isso, que o requisito se encontra preenchido mesmo que, por exemplo, seja ainda possível interpor recurso da medida de proteção no Estado Contratante de origem ou que o mesmo já tenha sido interposto, desde que tenha efeitos devolutivos. Nada é estabelecido sobre documentos a apresentar, nomeadamente sobre o modo de atestar a medida de proteção e a se tem ou não força executiva no Estado Contratante de origem. Atendendo ao que se referiu sobre a prova da medida de proteção (cf. /supra/ 2 da anotação ao artigo 23.º), considera-se que a autoridade do Estado Contratante requerido deve adotar uma postura flexível na determinação da força executiva da medida de proteção no Estado Contratante de origem [cite:@hilbig-lugani2016, artigo 26.º, para. 4, considera que a CH 1996 não exige a apresentação de cópia da medida de proteção ou de certidão de que mesma tem força executiva no Estado Contratante de origem]. Esta questão surgiu na jurisdição inglesa, na decisão /RE P (Recognition and Registration of Orders under the 1996 Hague Child Protection Convention) [2014] EWHC 2845 (Fam)/. Neste caso, o Direito interno inglês exigia a apresentação de informação e documentação diversa (cf. paras. 21 e 23 da decisão), permitindo também que o tribunal dispensasse a apresentação de documentos se considerasse ter informação suficiente (cf. para. 27 da decisão). O requerente não prestou grande parte da informação e documentos exigidos e a cópia da medida de proteção foi obtida pelo Tribunal junto do Tribunal do Estado Contratante de origem (cf. para. 32). O Tribunal considerou que tais exigências contrariavam a obrigação de um processo de /exequatur/ simples e rápido e decidiu dispensar todas informações e documentos que não estivessem preenchidas e declarar executória a medida de proteção (cf. para. 33).

** c) Carecer de força executória no Estado Contratante requerido


** d) A declaração de executoriedade ou registo tem de ser pedida por uma parte interessada
O processo de declaração de executoriedade ou registo da medida de proteção só pode ser iniciado a pedido de uma parte interessada. Como tal, a autoridade do Estado Contratante requerido não pode, oficiosamente, atribuir força executiva a uma medida de proteção tomada num outro Estado Contratante. Veja-se, por exemplo, o Ac. TRC 24/10/2023, proc. n.º 4/23.5YRCBR, Henrique Antunes, no qual se reconheceu, através do processo de revisão e confirmação de sentenças estrangeiras, uma medida de proteção tomada por um tribunal inglês, mas não se concedeu o /exequatur/ porque o mesmo não foi pedido pelo requerente.

O conceito de parte interessada inclui qualquer pessoa que tenha interesse na execução da medida [cite:@hilbig-lugani2016, artigo 26.º, para. 5], incluindo autoridades públicas, desde que estas tenham competência nos termos do Direito do Estado Contratante (como é o caso do Ministério Público em Portugal).

* 3. Processo simples e rápido (n.º 2)
A CH 1996 estabelece que o processo de declaração de executoriedade ou registo deve ser /simples e rápido/. Simples aponta no sentido de não serem exigidas muitas formalidades. Rápido aponta no sentido de que o processo ser tão célere quanto possível [cite:@hilbig-lugani2016, artigo 26.º, para. 8].

A obrigação recai sobre os Estados Contratantes, mas é considerada /lex imperfecta/ pois os Estados Contratantes são inteiramente livres de escolher os meios para atingir este desiderato e não é fixado qualquer prazo para a declaração de executoriedade ou registo [cite:@lagarde1996, para. 132]. A CH 1996 também não exige que seja adotado um processo não contraditório na sua fase inicial. O Relatório Explicativo tem o cuidado de informar que o termo "/requête/", utilizado na versão oficial em língua francesa do n.º 1 do artigo 26.º, não é usado no sentido estrito que tem no Direito processual francês (acto introdutório da instância no âmbito de um processo /ex parte/), pois a CH 1996 não pretendeu tomar posição sobre o processo que cada Estado Contratante deve adotar para a declaração de executoriedade ou registo da medida de proteção [cite:@lagarde1996, para. 132].

No contexto da liberdade concedida pela CH 1996 aos Estados Contratantes, tanto é legítima a posição de alguns Estados Contratantes, como o Reino Unido, que adotou um processo para o registo de medidas de proteção tomadas ao abrigo da CH 1996, como a de Portugal, que não adotou legislação para implementar o processo de declaração de executoriedade da CH 1996. A opção por implementar um processo de declaração de executoriedade ou registo da medida de proteção, em concretização da CH 1996, não garante necessariamente um processo simples e rápido. Como já se mencionou /supra/, na decisão /RE P (Recognition and Registration of Orders under the 1996 Hague Child Protection Convention) [2014] EWHC 2845 (Fam)/ o Tribunal considerou que a informação e documentação exigida no registo violava a obrigação de um processo /simples/.

No caso Português, a não adoção de legislação de implementação conduz à aplicação do processo especial de revisão e confirmação de sentenças estrangeiras (artigos 978.º e ss. do CPC) não só ao reconhecimento, mas também à concessão do /exequatur/. Esta solução não parece ser ideal, desde logo porque a competência para este processo está atribuída aos Tribunais da Relação e a configuração do mesmo (por abranger simultaneamente o reconhecimento e a concessão de /exequatur/) não parece ter tido em consideração especiais exigências de simplicidade e celeridade. O princípio da adequação formal (artigo 547.º do CPC) constitui o principal instrumento de que o Tribunal da Relação pode deitar mão para procurar, ainda assim, assegurar a simplicidade e celeridade do processo de declaração de executoriedade [cite:@ribeiro2022 p. 46].

* 4. Fundamentos de recusa da declaração de executoriedade ou do registo da medida de proteção (n.º 3)
* 5. Bibliografia
#+print_bibliography:

* 6. Lista de jurisprudência
Ac. TRC 24/10/2023, proc. n.º 4/23.5YRCBR, Henrique Antunes

/RE P (Recognition and Registration of Orders under the 1996 Hague Child Protection Convention) [2014] EWHC 2845 (Fam)/, disponível em https://www.bailii.org/ew/cases/EWHC/Fam/2014/2845.html e consultado pela última vez em 24 de junho de 2025.
