#+title: Anotação artigo 23.º da CH1996
#+author: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil author:nil date:nil title:nil

#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{titletoc}
#+LATEX_HEADER: \KOMAoptions{headings=small}

#+bibliography: ~/Dropbox/Bibliografia/BetterBibLatex/bib.bib
#+cite_export: csl np405.csl

#+begin_quote

Artigo 23.º

1. As medidas tomadas pelas autoridades de um Estado Contratante serão reconhecidas por força de lei em todos os outros Estado Contratantes.

2. Todavia, o reconhecimento poderá ser recusado:

  a) Se a medida tiver sido tomada por uma autoridade cuja competência não assenta em nenhum dos fundamentos previstos no capítulo II;

  b) Se a medida tiver sido tomada, salvo em caso de urgência, num contexto de um processo judiciário ou administrativo, sem se ter concedido à criança a possibilidade de ser ouvida, violando os princípios fundamentais dos procedimentos do Estado requerido;

  c) Se qualquer pessoa apresentar pedido indicando que a medida infringe as suas responsabilidades parentais, se tal medida ter sido tomada, salvo em casos de urgência, sem se ter concedido a essa pessoa a possibilidade de ser ouvida;

  d) Se tal reconhecimento é manifestamente contrário à ordem pública do Estado requerido, tendo em conta os melhores interesses da criança;

  e) Se a medida for incompatível com outra medida posterior tomada no Estado não Contratante da residência habitual da criança, quando esta última medida preencha os requisitos necessários ao reconhecimento no Estado requerido;

  f) Se os procedimentos previstos no artigo 33.º não tiverem sido respeitados.

#+end_quote

*Sumário:*

* 1. Breves notas gerais sobre o Capítulo IV
** a) Articulação com o regime de reconhecimento e execução do Regulamento Bruxelas II /ter/
A CH 1996 regula a competência, a lei aplicável, o reconhecimento (em sentido amplo) e a cooperação em matéria de responsabilidade parental e medidas
de protecção das crianças. O Regulamento Bruxelas II /ter/ regula a competência e o reconhecimento (em sentido amplo) em matéria matrimonial e em
matéria de responsabilidade parental, bem como o rapto internacional de crianças. Há, por isso, uma coincidência parcial de matérias reguladas por estes dois instrumentos. Ambos regulam a competência e o reconhecimento (em sentido amplo) em matéria de responsabilidade parental. O conceito de responsabilidade parental adotado pelo Regulamento Bruxelas II /ter/ é inspirado no consagado pela CH 1996 [cite:@almeida2022 pp. 21-22;@magnus2023a pp.86-87;@gomes2023 pp. 1561-1562].

A articulação entre estes dois instrumentos efetua-se atendendo ao artigo 52.º CH 1996 (para cuja anotação se remete) e ao artigo 97.º Regulamento Bruxelas II /ter/. O artigo 52.º foi precedido de longas e complexas negociações. Os Estados-Membros da União Europeia pretendiam reservar para si o direito de celebrar uma convenção sobre competência internacional em matéria de responsabilidade parantal e ações matrimoniais. Os outros Estados Contratantes da Conferência da Haia receavam o enfraquecimento da CH 1996, caso fosse conferida a possibilidade de Estados Contratantes celebrarem entre si e com Estados terceiros novas convenções sobre a mesma matéria. A redação do artigo 52.º CH 1996 traduz o compromisso alcançado [cite:@lagarde1996 ponto 170]. O n.º 2 do artigo 52.º confere a possibilidade de os Estados Contratantes celebrarem acordos entre si, em matéria de responsabilidade parental, relativamente a crianças habitualmente residentes no território desses Estados Contratantes. O requisito da residência habitual das crianças suscita dúvidas, particularmente no contexto da aplicação das normas de reconhecimento [cite:@gomes2023 p. 1598].

Neste contexto, e porque só podem ser Partes na CH 1996 Estados soberanos, o Conselho autorizou os Estados-Membros da União Europeia a ratificar ou aderir à CH 1996, mas exigiu - para garantir a aplicação das regras de Direito da União Europeia relativas ao reconhecimento e à execução de decisões judiciais na União Europeia - que os Estados-Membros fizessem a seguinte declaração ao assinar a Convenção:
#+begin_quote
"Os artigos 23.º, 26.º e 52.º da Convenção permitem às Partes Contratantes uma certa margem de flexibilidade para aplicarem um sistema simples e rápido de reconhecimento e de execução das decisões. A regulamentação comunitária prevê um sistema de reconhecimento e de execução, pelo menos, tão favorável como as regras constantes da Convenção. Assim sendo, as decisões em matérias abrangidas pela Convenção, quando proferidas por um tribunal de um Estado-Membro da União Europeia, serão reconhecidas e executadas em/na/nos [Estado-Membro que faz a declaração], aplicando-se a regulamentação interna pertinente do direito comunitário."[fn:1]
#+end_quote

Na alínea /b)/ do n.º 1 do artigo 97.º Regulamento Bruxelas II /ter/ estabelece-se que as regras de reconhecimento e execução do Regulamento Bruxelas II /ter/ prevalecem sempre (e independentemente do onde residir habitualmente a criança) sobre as da CH 1996, quando o Estado de origem e o Estado de reconhecimento sejam Estados-Membros da União Europeia vinculados ao Regulamento Bruxelas II /ter/. Assim, por exemplo, uma medida de proteção decretada na Itália deve ser reconhecida e executada em Portugal segundo o regime previsto no Regulamento Bruxelas II /ter/, mesmo que a criança resida habitualmente em Marrocos (Estado Contratante da CH 1996).  Esta solução — que parece visar uma mais fácil “circulação” das decisões no espaço europeu, assente no princípio da confiança mútua — acarreta, nos casos em que a criança tenha residência habitual num Estado terceiro que seja um Estado contratante da Convenção da Haia de 1996, um risco de se reconhecerem decisões, ao abrigo do regime do Regulamento Bruxelas II /ter/, cujo reconhecimento poderia ser recusado ao abrigo do regime da CH 1996, /v.g./, porque neste útlimo regime se admite como fundamento de recusa o controlo de competência da autoridade de origem (alínea /a)/ do n.º 2 do artigo 23.º CH 1996).

Assim, em Portugal, o regime da CH 1996 é aplicável ao reconhecimento e execução de medidas de proteção tomadas por autoridades de um Estado Contratante da CH 1996 que não seja, simultaneamente, um Estado-Membro da União Europeia. Retomando o exemplo dado /supra/, o reconhecimento e execução em Portugal de uma medida de proteção de criança residente habitualmente em Marrocos, tomada por uma autoridade marroquina, deve ser efetuado segundo o regime da CH 1996.

** b) Objeto do reconhecimento e execução
Beneficiam do regime de reconhecimento e execução previsto na CH 1996 as "medidas tomadas pelas autoridades de um Estado Contratante" (art. 23.º). Convém, por isso, analisar os conceitos de /(i)/ medidas de proteção e de /(ii)/ autoridades de um Estado Contratante e a /(iii)/ delimitação temporal do regime. Os conceitos da CH 1996, atendendo ao seu objetivo de uniformização das regras em matéria de responsabilidade parental nos Estados Contratantes, devem ser interpretados autonomamente.

O conceito de medidas de proteção não é definido pela CH 1996[cite:@lagarde1996, ponto 18]. O conceito é utilizado, desde logo, no âmbito de aplicação material da CH 1996, no qual se estabelece que a CH 1996 tem por objeto "Determinar qual o Estado cujas autoridades têm competência para tomar as /medidas orientadas à protecção da pessoa ou bens da criança/;" e "Assegurar o reconhecimento e a execução de /tais medidas de protecção/ em todos os Estados Contratantes;" (alíneas /a)/ e /d)/ do n.º 1 do artigo 1.º; itálicos aditados). O conceito é depois concretizado, através de uma enumeração exemplificativa (artigo 3.º) e de uma delimitação negativa (artigo 4.º). Da conjugação destes preceitos (para cujas anotações se remete) resulta que o conceito de medidas de proteção é um conceito /amplo/, que abrange qualquer medida que vise a proteção da pessoa ou bens da criança, exceto as excluídas no artigo 4.º da CH 1996[cite:@lagarde1996, ponto 26;@silberman2006, pp. 398-399].

O conceito de autoridade também não é definido pela CH 1996, ao contrário do que sucede no Regulamento Bruxelas II /ter/ (considerando n.º 14 e ponto 1) do n.º 2 do artigo 2.º do Regulamento Bruxelas II /ter/). Pode inferir-se do n.º 1 do artigo 5.º da CH 1996, que o conceito abrange autoridades judiciais e autoridades administrativas[cite:@nygh1997, p. 346]. Neste sentido, recorda-se que as regras de reconhecimento e execução da CH 1996 assentam, no espírito das "convenções duplas", na uniformização das regras de competência internacional[cite:@lagarde1996, ponto 119;@nygh1997, p. 355;@nygh1998, p. 23] e que a CH 1996 permite o controlo de competência da autoridade de origem (cf. /infra/), ou seja, permite recusar o reconhecimento de medidas tomadas por autoridades que não sejam internacionalmente competentes ao abrigo das normas de competência internacional da CH 1996.

O regime de reconhecimento e execução previsto na CH 1996 não tem eficácia retroativa. Resulta do n.º 2 do artigo 53.º (para cuja anotação se remete) que só beneficiam deste regime as medidas tomadas em data posterior à entrada em vigor da CH 1996 no Estado Contratante onde as medidas foram tomadas /e/ no Estado Contratante requerido. Assim, e por exemplo, uma medida de proteção tomada, em 2 de junho de 2025, pelas autoridades da República de El Salvador (Estado Contratante da CH 1996) cujo reconhecimento seja pedido em Portugal, não beneficia do regime de reconhecimento e execução previsto na CH 1996, apesar de este regime vigor em Portugal desde 1 de agosto de 2011, pois a Convenção só entrou em vigor na República de El Salvador em 1 de julho de 2025.

* 2. Reconhecimento automático (n.º 1)
* 3. Fundamentos de recusa do reconhecimento (n.º 2)
** a) Aspetos gerais
*** aa) Enumeração exaustiva dos fundamentos de recusa
*** bb) Possibilidade, não obrigatoriedade, de recusa
** b) Controlo da competência da autoridade de origem
** c) Audição da criança
** d) Audição da pessoa com responsabilidades parentais
** e) Ordem pública internacional
** f) Incompatibilidade de medidas de proteção
** g) Preterição dos procedimentos previstos no artigo 33.º
* 4. Bibliografia
#+print_bibliography:

* 5. Lista de jurisprudência

* Footnotes

[fn:1] Cf. artigo 2.º da Decisão 2003/93/CE do Conselho, de 19 de dezembro de 2002, que autoriza os Estados-Membros a assinarem, no interesse da Comunidade, a Convenção da Haia de 1996 relativa à jurisdição, à lei aplicável, ao reconhecimento, à execução e à cooperação em matéria de responsabilidade parental e de medidas de proteção dos filhos (JO L 48 de 21.2.2003) e artigo 2.º da Decisão 2008/431/CE do Conselho, de 5 de junho de 2008, que autoriza certos Estados-Membros a ratificar ou aderir, no interesse da Comunidade Europeia, à Convenção da Haia de 1996 relativa à competência, à lei aplicável, ao reconhecimento, à execução e à cooperação em matéria de responsabilidade parental e de medidas de proteção da criança, e que autoriza certos Estados-Membros a fazer uma declaração sobre a aplicação da regulamentação interna pertinente do direito comunitário — Convenção relativa à competência, à lei aplicável, ao reconhecimento, à execução e à cooperação em matéria de responsabilidade parental e de medidas de proteção da criança (JO L 151 de 11.6.2008).
