#+title: Anotação ao artigo 24.º da CH1996
#+author: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil author:nil date:nil title:nil

#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{titletoc}
#+LATEX_HEADER: \KOMAoptions{headings=small}

#+bibliography: ~/Dropbox/Bibliografia/BetterBibLatex/bib.bib
#+cite_export: csl np405.csl

#+begin_quote

#+begin_center
*Artigo 24.º*
#+end_center

Sem prejuízo do n.º 1 do artigo 23.º, qualquer pessoa interessada poderá solicitar às autoridades competentes de um Estado Contratante que decidam sobre o reconhecimento, ou não, de uma medida tomada noutro Estado Contratante. Este processo será regido pela lei do Estado requerido.

#+end_quote

*Sumário:* 1. Reconhecimento ou não reconhecimento em processo autónomo; 2. Regulação do processo autónomo.

* 1. Reconhecimento ou não reconhecimento em processo autónomo
Apesar do reconhecimento das medidas de proteção ser automático (cf. /supra/ n.º 1 do artigo 23.º e respetiva anotação), a CH 1996 consagra expressamente a possibilidade de qualquer pessoa interessada solicitar, em processo autónomo e a título principal, o reconhecimento ou não reconhecimento de uma medida de proteção tomada pelas autoridades de um outro Estado Contratante. No contexto da legislação europeia, consagrou-se faculdade semelhante no n.º 3 do artigo 30.º e no n.º 1 do artigo 40.º do Regulamento Bruxelas II /ter/ [cite:@almeida2022a pp. 104-106].

Analisando a norma em maior detalhe, verifica-se que o processo autónomo tem como objeto o reconhecimento ou o não reconhecimento de uma medida de proteção (sobre este conceito cf. /supra/ o ponto 1.b) da anotação ao artigo 23.º). Tal significa que este procedimento não é aplicável aos casos de atribuição ou extinção de responsabilidade parental por força da lei [cite:cf. artigo 16.º da CH 1996 e @lagarde1996, ponto 129].

Qualquer parte interessada pode solicitar este processo autónomo. O onceito de parte interessada é amplo e parece incluir qualquer pessoa cuja situação jurídica seja afetada pelo reconhecimento ou não reconhecimento da medida, como por exemplo, a criança, as pessoas com responsabilidade parentais sobre a criança, as pessoas que pretedem ter responsabilidades parentais sobre a criança, outros familiares (como avós ou irmaões) se os seus direitos forem afetados e até terceiros que estejam envolvidos em negócios jurídicos com a criança [cite:@hilbig-lugani2016, artigo 24.º, n.º 4].

No Relatório Explicativo considera-se que o principal interesse deste processo autónomo será o de /antecipar/ a resposta, com certeza e segurança jurídica, a questão de saber se uma medida de proteção tomada num outro Estado Contratante será (ou não) reconhecida no Estado Contratante requerido. Quando o reconhecimento é automático, a questão da existência ou não de um fundamento de recusa surgirá a título incidental no momento em que a medida de proteção é invocada. Recorrendo a este procedimento autónomo, é possível dirimir a questão do reconhecimento ou não reconhecimento da medida de proteção em momento anterior. Os exemplos dados no Relatório Explicativo têm esta vantagem em mente: no primeiro exemplo, foi dada custódia à mãe no Estado Contratante A, estabelecendo-se que não pode mudar a residência habitual da criança para outro país sem o consentimento do pai. Este está de acordo com a mudança para o Estado Contratante B. Quer, no entanto, saber se o Estado Contratante B reconhece a medida de proteção tomada pelo Estado Contratante A, de modo a que a mãe não possa mudar a residência habitual da criança para outro Estado sem o seu consentimento. No segundo exemplo, foi tomada uma medida de proteção no Estado Contratante A, que privou o pai do exercício das responsabilidade parentais contra a sua vontade. Este progenitor pode ter interesse em saber se o reconhecimento desta medida será recusado no Estado Contratante B, pois quer impedir que a mãe celebre nesse Estado um negócio jurídico em nome da criança [cite:@lagarde1996, ponto 129]. O mesmo sucede com o exemplo do Manual Prático [cite:@hcchpermanentbureau2018, exemplo 10 i)].

Pensa-se que poderá haver outro elemento a destacar: a CH 1996 não dispõe sobre o valor da decisão de reconhecimento ou não reconhecimento seja ela proferida a título incidental ou a título principal. Assim, entende-se que essa questão deve ser resolvida de acordo com as normas de Direito vigentes no Estado Contratante requerido. Quando Portugal seja o Estado-Membro requerido as decisões de reconhecimento ou de não reconhecimento proferidas a título incidental não constituem, em regra, caso julgado fora do processo respetivo (artigo 91.º do CPC), ao contrário do que sucede quando sejam proferidas a título principal.

* 2. Regulação do processo autónomo
A CH 1996 não regula a tramitação deste processo autónomo, antes remetendo para a lei do Estado Contratante requerido. Como se trata de um processo de reconhecimento ou não reconhecimento de uma medida de proteção (e não de um processo com vista à obtenção de declaração de executoriedade) não é aplicável a exigência, prevista no n.º 2 do artigo 26.º da CH 1996, de que o procedimento seja simples e rápido [cite:@lagarde1996, ponto 130]. No Relatório Explicativo considera-se que este processo autónomo deve ter carácter contraditório, pois o processo autónomo visa iniciar o debate sobre o reconhecimento ou não reconhecimento da medida de proteção e daí decorre, logicamente, que deverá de ser dada oportunidade à outra parte para contestar [cite:@lagarde1996, ponto 130]. Concorda-se com a argumentação, mas assinala-se que a CH 1996 nada dispõe sobre a matéria, o que permite algum espaço de manobra aos Estados Contratantes [cite:@hilbig-lugani2016, artigo 24.º, n.º 7], que podem, por exemplo, adotar um processo de carácter não contraditório em primeira instância, com possibilidade de recurso necessariamente contraditório. Em Portugal esta questão não se coloca, uma vez que o reconhecimento ou não reconhecimento em processo autónomo faz-se segundo o processo especial de revisão e confirmação de sentença estrangeira [cite:cf. artigos 978.º e ss. do CPC, Ac. TRC 24/10/2023, proc. n.º 4/23.5YRCBR, Henrique Antunes e @almeida2023b; @geraldes2022; @mendes2022a pp. 395-399; @pinheiro2019a pp. 188-237].

*A fazer:* verificar págs. na 2.ª edição do CPC anotado.

* 3. Bibliografia
#+print_bibliography:

* 4. Lista de jurisprudência
Ac. TRC 24/10/2023, proc. n.º 4/23.5YRCBR, Henrique Antunes
