#+title: Anotação ao artigo 27.º da CH1996
#+author: João Gomes de Almeida
#+LANGUAGE: pt
#+OPTIONS: toc:nil num:nil author:nil date:nil title:nil

#+LATEX_CLASS: koma-article
#+LATEX_COMPILER: xelatex
#+LATEX_HEADER: \usepackage{titletoc}
#+LATEX_HEADER: \KOMAoptions{headings=small}

#+bibliography: ~/Dropbox/Bibliografia/BetterBibLatex/bib.bib
#+cite_export: csl np405.csl

#+begin_quote

#+begin_center
*Artigo 27.º*
#+end_center

Sem prejuízo da análise que seja necessária para a aplicação dos artigos precedentes, não haverá qualquer revisão quanto ao mérito da medida tomada.

#+end_quote

*Sumário:*

* 1. Introdução
A CH 1996 proíbe que o tribunal do Estado Contratante requerido proceda ao controlo do mérito da sentença, solução que é já tradicional nas convenções da Conferência da Haia que versam sobre o reconhecimento e execução [cite:cf. artigo 6.º da Convenção da Haia de 1970 sobre o Reconhecimento dos Divórcios e Separações de Pessoas, artigo 8.º da Convenção da Haia de 1971 sobre o Reconhecimento e a Execução de Sentenças Estrangeiras em Matéria Civil e Comercial, artigo 12.º da Convenção da Haia de 1973 sobre o Reconhecimento e Execução das Sentenças Relativas a Obrigações Alimentares, artigo 26.º da Convenção da Haia de 2000 relativa à Proteção Internacional de Adultos, artigo 8.º da Convenção da Haia de 2005 sobre Acordos de Eleição do Foro, n.º 2 do artigo 4.º Convenção da Haia de 2019 sobre o Reconhecimento e a Execução de Sentenças Estrangeiras em Matéria Civil ou Comercial e @lagarde1996, para. 133, que a considera uma cláusula típica das convenções sobre reconhecimento e execução].

No contexto europeu, a proibição de controlo do mérito foi consagrada na Convenção de Bruxelas [cite:cf. artigo 29.º e @jenard1990 p. 163] e, desde então, nos regulamentos da União Europeia que versam sobre o reconhecimento e execução, como o Regulamento Bruxelas I /bis/ [cite:cf. artigo 52.º e @gaudemet-tallon2018 pp. 589-592] e o Regulamento Bruxelas II /ter/ [cite:cf. artigos 70.º e 71.º e @almeida2022a pp. 110-111].

A proibição de controlo do mérito tem sido considerada essencial para a eficácia de qualquer instrumento internacional em matéria de reconhecimento e execução [cite:cf., em sede da Convenção da Haia de 2019 sobre o Reconhecimento e a Execução de Sentenças Estrangeiras em Matéria Civil ou Comercia, @garcimartin2020a, para. 119; e, no contexto da Convenção de Bruxelas e do Regulamento Bruxelas I /bis/, @jenard1990 p. 163; @mendes2022a p. 39;@magnus2023, artigo 52.º, para. 1]. A proibição da /révision au fund/ é crucial para facilitar a "circulação" das medidas de proteção entre os Estados Contratantes da CH 1996 e encontra fundamento na ideia de confiança mútua entre Estados Contratantes, que, no caso da CH 1996, assenta na uniformização das normas de determinação da competência internacional e de direito de conflitos.

* 2. Proibição de controlo do mérito
** a) Enunciado

O controlo do mérito encontra-se vedado, seja na vertente fraca, em que se controla apenas a lei aplicada, seja na vertente forte, em que se controla também se a lei foi corretamente interpretada e aplicada [cite:@pinheiro2019a p. 70]. Ou seja, em regra, a autoridade do Estado Contratante requerido não pode verificar se a autoridade que tomou a medida de proteção no Estado Contratante de origem determinou a lei aplicável em conformidade com as normas uniformes da CH 1996, se aplicou corretamente ao caso concreto a lei aplicável, nem se decidiu corretamente a matéria de facto. A autoridade do Estado Contratante requerido não pode questionar a validade ou correção da medida de proteção tomada no Estado Contratante de origem nem, consequentemente, pode recusar o reconhecimento ou declaração de executoriedade porque teria aplicado lei diferente, teria tomado diferente medida de proteção ou a medida de proteção tomada seria inadmissível ou desconhecida do direito material que aplicaria ou porque existe um vício nos fundamentos de facto ou de direito da medida de proteção.

O reconhecimento ou declaração de executoriedade da medida de proteção só podem ser recusados com base num ou mais dos fundamentos elencados no artigo 23.º da CH 1996. Daqui resulta também que a proibição de controlo do mérito impede a autoridade do Estado Contratante requerido de reapreciar questões processuais subjacentes à medida de proteção (exceto se estas forem reconduzíveis a um dos fundamentos de recusa elencados no artigo 23.º da CH 1996).

** b) Exceções

A Convenção estabelece ainda que "There may only be such consideration [of the merits of the judgment] as is necessary for the application of this Convention" . Numa primeira leitura, pode parecer que o tribunal do Estado Contratante requerido pode controlar o mérito da sentença proferida por um tribunal do Estado Contratante de origem, nos casos em que tal seja necessário para aplicar uma regra da Convenção. Não nos parece ser essa a interpretação mais correta. Algumas regras da Convenção - em particular as referentes ao controlo de competência do tribunal de origem - exigem, para a sua aplicação, que se tomem em consideração factos constantes do processo. Assim, por exemplo, para verificar o critério de competência indireta previsto no artigo 5.º, n.º 1, alínea a), o tribunal do Estado Contratante requerido terá de determinar a residência habitual da parte contra quem o reconhecimento e ou execução é requerida. Para tal, terá de analisar (tomar em consideração) os elementos constantes do processo. Porém, o tribunal do Estado contratante requerido não está vinculado às conclusões do tribunal do Estado contratante de origem. Não se trata aqui, verdadeiramente, de um controlo do mérito da sentença . A competência indireta é, inequivocamente, determinada pelo tribunal do Estado Contratante requerido. Não obstante, a sua proximidade e o potencial resultado de não reconhecimento e ou execução justificam a ressalva efetuada .

** c) Relação com os artigos 14.º e 15.º da CH 1996
* 4. Bibliografia
* 5. Lista de jurisprudência
